name: cardoctor_services
description: A new Flutter project.
version: 0.0.1
homepage: 

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  get:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  flutter_svg: ^1.0.3 # cannot bump version, conflict with flutter_flavorizr
  google_fonts: ^3.0.1
  intl: ^0.17.0
  simple_animations: ^4.1.0
  modal_bottom_sheet: ^2.0.1
  webview_flutter: ^3.0.4
  jiffy: ^5.0.0
  url_launcher: ^6.1.8
  simple_shadow: ^0.3.0
  permission_handler: ^10.2.0
  lottie: ^1.3.0
  #    git:
  #      ref: '8892124'
  #      url: https://github.com/RobertHeim/flutter_showcaseview

  # firebase
  firebase_core: ^2.4.1


  # cardoctor_sdk_sos
  cardoctor_sdk_sos: ^1.0.6
  firebase_dynamic_links: ^5.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4
  flutter_flavorizr: ^2.1.3
  flutter_launcher_icons: ^0.9.3
  flutter_gen_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/home/
    - assets/images/card_corner/
    - assets/images/error/
    - assets/images/onboarding/
    - assets/images/buy_ticket/
    - assets/images/cash_in/
    - assets/images/id_card/
    - assets/icons/
    - assets/icons/tabbar/
    - assets/lottie/
    - cardoctor/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
